package starting;

import admin.adminForm;
import admin.fulluserlists;
import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.userForm;

/**
 *
 * @author DERECHO
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
    }
    
    public static String  lname, username, password, status ,type;
    
    Color navColor = new Color(204,204,204);
    Color logColor = new Color(204,255,204);
    
public static boolean loginAcc(String username, String password){
    dbConnector connector = new dbConnector();
    try{
        String query = "SELECT * FROM tbl_user WHERE u_username = ? AND u_password = ? AND u_status = 'Active'";
        PreparedStatement preparedStatement = connector.prepareStatement(query);
        preparedStatement.setString(1, username);
        String hashedPassword = passwordHasher.hashPassword(password);
        preparedStatement.setString(2, hashedPassword);
        ResultSet resultSet = preparedStatement.executeQuery();
        if(resultSet.next()){
            lname = resultSet.getString("u_lname");
            type = resultSet.getString("u_type");
            Session shesh = Session.getInstance();
            shesh.setUid(resultSet.getInt("u_id"));
            shesh.setFname(resultSet.getString("u_fname"));
            shesh.setLname(resultSet.getString("u_lname"));
            shesh.setEmail(resultSet.getString("u_email"));
            shesh.setContactnumber(resultSet.getLong("u_contactnumber"));
            shesh.setUsername(resultSet.getString("u_username"));
            shesh.setType(resultSet.getString("u_type"));
            shesh.setStatus(resultSet.getString("u_status"));
            if(type.equals("Admin") || type.equals("User")){
                return true;
            }else{
                System.out.println("Invalid user type!"); 
                return false;
            }
        }else{
            System.out.println("Invalid username, password, or account status!"); 
            return false;
        }
    }catch (SQLException | NoSuchAlgorithmException ex) {
        System.out.println("Exception: " + ex.getMessage());
        return false;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lbltitle1 = new javax.swing.JLabel();
        lbltitle2 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        createaccount = new javax.swing.JLabel();
        forgotpassword = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        lbllogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(204, 255, 204));
        background.setLayout(null);

        lbltitle1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lbltitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle1.setText("Beverage Inventory ");
        background.add(lbltitle1);
        lbltitle1.setBounds(290, 10, 400, 50);

        lbltitle2.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lbltitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle2.setText("Management System ");
        background.add(lbltitle2);
        lbltitle2.setBounds(290, 60, 400, 50);

        sidebar.setBackground(new java.awt.Color(0, 51, 0));
        sidebar.setLayout(null);

        logo.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("LOGO");
        logo.setToolTipText("");
        logo.setVerifyInputWhenFocusTarget(false);
        sidebar.add(logo);
        logo.setBounds(90, 60, 100, 31);

        lblusername.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("USERNAME: ");
        sidebar.add(lblusername);
        lblusername.setBounds(180, 180, 100, 20);

        lblpassword.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(255, 255, 255));
        lblpassword.setText("PASSWORD: ");
        sidebar.add(lblpassword);
        lblpassword.setBounds(180, 220, 100, 20);

        background.add(sidebar);
        sidebar.setBounds(0, 0, 280, 520);

        txtusername.setBackground(new java.awt.Color(204, 255, 204));
        txtusername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        background.add(txtusername);
        txtusername.setBounds(290, 170, 180, 30);

        txtpassword.setBackground(new java.awt.Color(204, 255, 204));
        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        background.add(txtpassword);
        txtpassword.setBounds(290, 210, 180, 30);

        createaccount.setFont(new java.awt.Font("Myanmar Text", 0, 10)); // NOI18N
        createaccount.setForeground(new java.awt.Color(255, 51, 51));
        createaccount.setText("Create Account?");
        createaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createaccountMouseClicked(evt);
            }
        });
        background.add(createaccount);
        createaccount.setBounds(290, 250, 80, 20);

        forgotpassword.setFont(new java.awt.Font("Myanmar Text", 0, 10)); // NOI18N
        forgotpassword.setForeground(new java.awt.Color(255, 51, 51));
        forgotpassword.setText("Forget Password?");
        forgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseClicked(evt);
            }
        });
        background.add(forgotpassword);
        forgotpassword.setBounds(390, 250, 80, 20);

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 5));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        lbllogin.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbllogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogin.setText("L O G I N");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbllogin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(login);
        login.setBounds(290, 280, 180, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void createaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccountMouseClicked
        System.out.println("Registration Start!");
        registrationForm rgf = new registrationForm();
        rgf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createaccountMouseClicked

    private void forgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotpasswordMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        if(txtusername.getText().isEmpty() || txtpassword.getText().isEmpty()){
            System.out.println("Empty Text Field!");
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }else{
            if(loginAcc(txtusername.getText(), txtpassword.getText())){
                System.out.println(type + " Exist!");
               JOptionPane.showMessageDialog(null, "Login Success!");
                if(type.equals("Admin")){
                    adminForm adf = new adminForm();
                    fulluserlists fusf = new fulluserlists();
                    adf.setVisible(true);
                    this.dispose();
                }else if(type.equals("User")){
                    userForm usf = new userForm();
                    usf.setVisible(true);
                    this.dispose();
                }
            }else{
                System.out.println("Invalid username, password, or account status!"); 
                txtusername.setText("");
                txtpassword.setText("");
                JOptionPane.showMessageDialog(null, "Invalid username, password, or account status!");
            }
        }
    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(logColor);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(navColor);
    }//GEN-LAST:event_loginMouseExited

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel createaccount;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lbltitle2;
    private javax.swing.JLabel lblusername;
    public javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
