/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalsaleForm;

/**
 *
 * @author DERECHO
 */
public class saleseditForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form saleseditForm
     */
    public saleseditForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        lblregistration = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtstocks = new javax.swing.JTextField();
        lblstocks = new javax.swing.JLabel();
        boxtype = new javax.swing.JComboBox<>();
        lbltype = new javax.swing.JLabel();
        boxstatus = new javax.swing.JComboBox<>();
        lblstatus = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        lblconpass = new javax.swing.JLabel();
        confirm = new javax.swing.JPanel();
        lblconfirm = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(null);

        id.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        id.setForeground(new java.awt.Color(46, 49, 146));
        background.add(id);
        id.setBounds(210, 10, 150, 50);

        lblregistration.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblregistration.setForeground(new java.awt.Color(46, 49, 146));
        lblregistration.setText("Product #");
        background.add(lblregistration);
        lblregistration.setBounds(10, 10, 420, 60);

        back.setForeground(new java.awt.Color(46, 49, 146));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setToolTipText("");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        background.add(back);
        back.setBounds(470, 10, 50, 40);

        txtname.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 49, 146), 2));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        background.add(txtname);
        txtname.setBounds(150, 80, 190, 30);

        lblname.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblname.setText("Name:");
        background.add(lblname);
        lblname.setBounds(30, 80, 120, 30);

        txtstocks.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtstocks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 49, 146), 2));
        txtstocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstocksActionPerformed(evt);
            }
        });
        background.add(txtstocks);
        txtstocks.setBounds(150, 130, 190, 30);

        lblstocks.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblstocks.setText("Available Stocks:");
        background.add(lblstocks);
        lblstocks.setBounds(30, 130, 120, 30);

        boxtype.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        boxtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Alcoholic Drinks", "Softdrinks", "Water" }));
        boxtype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 49, 146), 2));
        boxtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtypeActionPerformed(evt);
            }
        });
        background.add(boxtype);
        boxtype.setBounds(150, 180, 190, 30);

        lbltype.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbltype.setText("Product Type:");
        background.add(lbltype);
        lbltype.setBounds(30, 180, 120, 30);

        boxstatus.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        boxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Available", "Out-of-Stocks", "Limited Stock", " " }));
        boxstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 49, 146), 2));
        boxstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxstatusActionPerformed(evt);
            }
        });
        background.add(boxstatus);
        boxstatus.setBounds(150, 230, 190, 30);

        lblstatus.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblstatus.setText("Status:");
        background.add(lblstatus);
        lblstatus.setBounds(30, 230, 120, 30);

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 49, 146), 2));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        background.add(txtpassword);
        txtpassword.setBounds(150, 280, 190, 30);

        lblconpass.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblconpass.setText("Confirm Password:");
        background.add(lblconpass);
        lblconpass.setBounds(30, 280, 120, 30);

        confirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 49, 146), 5));
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmMouseExited(evt);
            }
        });
        confirm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblconfirm.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblconfirm.setText("C O N F I R M");
        confirm.add(lblconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        background.add(confirm);
        confirm.setBounds(390, 360, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        parentFrame.restoreOriginalState();
        System.out.println("Admin clicked Back!");
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtstocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstocksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstocksActionPerformed

    private void boxtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxtypeActionPerformed

    private void boxstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxstatusActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        String cNum = txtcontactnumber.getText();
        if (txtname.getText().isEmpty() || txtstocks.getText().isEmpty() || txtemail.getText().isEmpty()
            || txtusername.getText().isEmpty() || txtpassword.getText().isEmpty() || txtcontactnumber.getText().isEmpty()) {
            System.out.println("Empty Text Field!");
            JOptionPane.showMessageDialog(null, "All fields are required!");

        } else if (txtpassword.getText().length() < 8) {
            System.out.println("Password Invalid!");
            JOptionPane.showMessageDialog(null, "Password character should be 8 above!");
            txtpassword.setText("");

        } else if (!validCNum(cNum)) {
            System.out.println("Contact Number Invalid!");
            JOptionPane.showMessageDialog(null, "Contact Number should be numbers or less than 11 digits!");

        } else if (boxtype.getSelectedItem().equals("N/A")) {
            System.out.println("Account Type Invalid!");
            JOptionPane.showMessageDialog(null, "Account Type must be Admin or User!");

        } else if (boxstatus.getSelectedItem().equals("N/A")) {
            System.out.println("Account Status Invalid!");
            JOptionPane.showMessageDialog(null, "Account Status must be Active or Inactive!");

        } else {
            dbConnector connector = new dbConnector();
            try {
                long conNum = Long.parseLong(cNum);
                String password = passwordHasher.hashPassword(txtpassword.getText());

                if (isCreating) {
                    if (connector.insertData("INSERT INTO tbl_user(u_fname ,u_lname ,u_email ,u_contactnumber ,u_username "
                        + ",u_password ,u_type ,u_status) VALUES('" + txtname.getText() + "','" + txtstocks.getText()
                        + "','" + txtemail.getText() + "','" + conNum + "','" + txtusername.getText() + "','" + password + "','"
                        + boxtype.getSelectedItem() + "','" + boxstatus.getSelectedItem() + "')")) {
                    System.out.println("Information Inserted!");
                    JOptionPane.showMessageDialog(null, "Created Account Successfully!");
                    parentFrame.restoreOriginalState();
                    this.dispose();
                } else {
                    System.out.println("Information Rejected!");
                    JOptionPane.showMessageDialog(null, "Failed Successfully!");
                }
            } else {
                if(connector.updateData("UPDATE tbl_user SET u_fname = '" + txtname.getText() + "', u_lname = '"
                    + txtstocks.getText() + "', u_email = '" + txtemail.getText() + "', u_contactnumber = '"
                    + txtcontactnumber.getText() + "', u_username = '" + txtusername.getText() + "', u_password = '"
                    + txtpassword.getText() + "', u_type = '" + boxtype.getSelectedItem() + "', u_status = '"
                    + boxstatus.getSelectedItem() + "' WHERE u_id = '" + id.getText() + "'")){
                System.out.println("Information Updated!");
                JOptionPane.showMessageDialog(null, "Updated Account Successfully!");
                parentFrame.restoreOriginalState();
                this.dispose();
            } else {
                System.out.println("Information Rejected!");
                JOptionPane.showMessageDialog(null, "Failed Successfully!");
            }
        }
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("" + ex);
        }
        }
    }//GEN-LAST:event_confirmMouseClicked

    private void confirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseEntered
        confirm.setBackground(enterColor);
    }//GEN-LAST:event_confirmMouseEntered

    private void confirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseExited
        confirm.setBackground(borderColor);
    }//GEN-LAST:event_confirmMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel background;
    public javax.swing.JComboBox<String> boxstatus;
    public javax.swing.JComboBox<String> boxtype;
    private javax.swing.JPanel confirm;
    public javax.swing.JLabel id;
    private javax.swing.JLabel lblconfirm;
    private javax.swing.JLabel lblconpass;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblregistration;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JLabel lblstocks;
    private javax.swing.JLabel lbltype;
    public javax.swing.JTextField txtname;
    public javax.swing.JPasswordField txtpassword;
    public javax.swing.JTextField txtstocks;
    // End of variables declaration//GEN-END:variables
}
